---

- name: DEPLOYING SNMP CONFIGURATIONS ON IOS AND JUNOS
  # this is the right comment
  hosts: iosxe,vmx
  gather_facts: false

  vars:
    ansible_connection: network_cli
    vendor_commands:
      ios: |
        snmp-server community ntc-team RO
        snmp-server location FL_HQ
        snmp-server contact JAMES_CHARLES
      junos: |
        set snmp location FL_HQ
        set snmp contact JAMES_CHARLES
        set snmp community public authorization read-only

  tasks:
    - name: Task 1 - ensure snmp commands exist on ios and vmx devices
      cli_config:
        config: "{{ vendor_commands[ansible_network_os] }}"

    - debug:
        msg: A task without a name, so lazy!
